// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFpI9ZtxCKNe5hvS6Ck2J6kQ1qzjSufLQ',
    appId: '1:999816840421:web:c6f7ff9bbf12ecdf06000c',
    messagingSenderId: '999816840421',
    projectId: 'product-browse-app',
    authDomain: 'product-browse-app.firebaseapp.com',
    storageBucket: 'product-browse-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9cFTIhut62e7JeasOFg0D-kyHm4XfU-Q',
    appId: '1:999816840421:android:e8e2761fbd7a178006000c',
    messagingSenderId: '999816840421',
    projectId: 'product-browse-app',
    storageBucket: 'product-browse-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Txjasf3cD2PKK-2b10sxvbA8K9O526E',
    appId: '1:999816840421:ios:8b8ba90ea0a125e006000c',
    messagingSenderId: '999816840421',
    projectId: 'product-browse-app',
    storageBucket: 'product-browse-app.firebasestorage.app',
    iosBundleId: 'com.example.productBrowserApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Txjasf3cD2PKK-2b10sxvbA8K9O526E',
    appId: '1:999816840421:ios:8b8ba90ea0a125e006000c',
    messagingSenderId: '999816840421',
    projectId: 'product-browse-app',
    storageBucket: 'product-browse-app.firebasestorage.app',
    iosBundleId: 'com.example.productBrowserApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFpI9ZtxCKNe5hvS6Ck2J6kQ1qzjSufLQ',
    appId: '1:999816840421:web:2855947fad64c89f06000c',
    messagingSenderId: '999816840421',
    projectId: 'product-browse-app',
    authDomain: 'product-browse-app.firebaseapp.com',
    storageBucket: 'product-browse-app.firebasestorage.app',
  );
}
